import type { BeefReport } from "../types.js";
import { CATEGORY_EMOJI, CATEGORY_LABELS } from "../types.js";

export function toMarkdown(r: BeefReport, top = 15): string {
  const L: string[] = [];
  L.push(`# 🥩 wiki-beef — edit wars on ${r.lang}.wikipedia`);
  L.push("");
  L.push(`> Last ${r.windowHours}h · ${r.total} reverted edits across ${r.pages} contested pages · live from the MediaWiki API, no key.`);
  L.push("");
  const shown = r.beefs.slice(0, top);
  if (shown.length === 0) {
    L.push("Peace on Wikipedia right now — no edit wars in the window. 🕊️");
    L.push("");
  } else {
    L.push("| # | Article | Beef | Score | Reverts | Editors | What they're fighting about |");
    L.push("| --- | --- | --- | --- | --- | --- | --- |");
    shown.forEach((b, i) => {
      const about = b.about === "(no edit summary)" ? "" : b.about.replace(/\|/g, "\\|").slice(0, 100);
      L.push(`| ${i + 1} | [${b.title}](${b.historyUrl}) | ${CATEGORY_EMOJI[b.category]} ${CATEGORY_LABELS[b.category]} | ${b.score} | ${b.reverts} | ${b.editors} | ${about} |`);
    });
    L.push("");
  }
  L.push("---");
  L.push("<sub>generated by [wiki-beef](https://github.com/didrod205/wiki-beef) — public data, no key, nothing uploaded.</sub>");
  return L.join("\n") + "\n";
}
